import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { ReelGeneratedModule, ReelGeneratedSharedModule } from './generated/module.js';
import { ReelValidator, registerValidationChecks } from './reel-validator.js';
import { ReelScopeProvider } from '../reel-scope.js';
import {ReelCompletionProvider} from "../reel-completion.js";

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ReelAddedServices = {
    validation: {
        ReelValidator: ReelValidator
    }
}


/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ReelServices = LangiumServices & ReelAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ReelModule: Module<ReelServices, PartialLangiumServices & ReelAddedServices> = {
    references: {
        ScopeProvider: (services) => new ReelScopeProvider(services),
    },
    
    validation: {
        ReelValidator: () => new ReelValidator()
    },
    lsp: {
        CompletionProvider: (services) => new ReelCompletionProvider(services),
    }
    
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createReelServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Reel: ReelServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ReelGeneratedSharedModule
    );
    const Reel = inject(
        createDefaultModule({ shared }),
        ReelGeneratedModule,
        ReelModule
    );

    shared.ServiceRegistry.register(Reel);
    registerValidationChecks(Reel);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Reel };
}
